version: '2'
# 基本的にいじるところはポート設定(外から接続するデバッグ用)の箇所で良い
# docker同士はservice名で参照し合うので、ポートは関係ない。
services:
  # ファイルデータを一元的に管理するもの。
  # 基本アプリ、拡張API側ではこれを共有する。
  data:
    image: busybox
    stdin_open: true
    tty: false
    volumes:
      # mysql設定
      - ./mysql/my.cnf:/etc/my.cnf
      # ホストと共有するフォルダ設定
      # search_DegitalLibrary内のフォルダが/home/pythonにマウントされる
      - ../:${PROJECT_DIR}
    command: /bin/sh
  # DB。
  db:
    image: mysql
    ports:
      - "3300:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: search_degital_library
      MYSQL_USER: spark
      MYSQL_PASSWORD: wsl-slave
      MYSQL_ROOT_PASSWORD: wsl-slave
    volumes_from:
      - data
  elasticsearch:
    image: elasticsearch:5.1
    # ports:
    #     - 9200:9200
    expose: 
      - "9200"
  # 基本アプリ
  app:
    # restart: always
    build: ./app
    # docker run -tオプションに相当
    # tty: true 
    volumes_from:
      - data
    volumes:
      - ./app/config/enviroment.yml:${MAIN_APP}/config/enviroment.yml
      - ./app/setting.ini:${MAIN_APP}/setting.ini
      - ./app/models_config.py:${MAIN_APP}/models/config.py
    ports:
      - "10081:80"
      - "15000:5000"
    expose:
      - "5000"
    links:
      - db
      - extension_api
      - elasticsearch
    working_dir: ${MAIN_APP}
    command: 
      bash -c "
      echo 'sudo service nginx restart' &&
      sudo service nginx restart && 
      echo 'sleep 30s elastic mysql 起動待ち' &&
      sleep 30s &&
      echo 'mysql import to search_degital_library.sql' &&
      sudo mysql -h db -P 3306 -u spark -pwsl-slave search_degital_library < ${PROJECT_DIR}/docker/mysql/search_degital_library.sql &&
      echo 'python3 insert_elastic' &&
      python3 ${PROJECT_DIR}/docker/app/insert_elastic.py && 
      echo 'python3 server.py' &&
      python3 ${MAIN_APP}/server.py"
      # ../../elasticsearch-2.3.4/bin/elasticsearch -Des.insecure.allow.root=true && 
  # 拡張用
  extension_api:
    # restart: always
    build: ./extension_api
    # tty: true 
    volumes_from:
      - data
    volumes:
      - ./extension_api/config.ini:${EXTENTION_APP}/config.ini
    ports:
      - "13000:3000"
    links:
      - db
    working_dir: ${EXTENTION_APP}
    command: 
      bash -c "
      echo 'sleep 25s mysql 起動待ち' &&
      sleep 25s &&
      echo 'python3 api.py' &&
      python3 ${EXTENTION_APP}/api.py --config-path ${PROJECT_DIR}/docker/extension_api/config.ini"
